"""Persist evidence records as JSON plus same-name HTML previews."""
from __future__ import annotations

import html
import hashlib
import json
import os
import re
from datetime import datetime
from pathlib import Path

from weixin.core.main import JSONS_DIR
from weixin.db.models import EvidenceRecord


class SafeHtml(str):
    """Small marker for HTML snippets generated by this module."""


def save_record(record: EvidenceRecord, overwrite_json_path: str = ""):
    """Save one evidence record to JSON and generate a sibling HTML preview.

    If *overwrite_json_path* is given, overwrite that file instead of creating a new one.
    """
    os.makedirs(JSONS_DIR, exist_ok=True)

    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    data = record.to_dict()
    identifier = build_video_identifier(data)
    data.setdefault("candidate", {})["video_identifier"] = identifier

    if overwrite_json_path:
        path = overwrite_json_path
        keyword_slug = filename_slug(data.get("search_keyword", ""), fallback="keyword", max_len=14)
        blogger_slug = filename_slug(primary_blogger_name(data), fallback="blogger", max_len=14)
        # 仅用于日志显示
        _display = f"result_{ts}_{keyword_slug}_{blogger_slug}_{identifier}.json"
    else:
        keyword_slug = filename_slug(data.get("search_keyword", ""), fallback="keyword", max_len=14)
        blogger_slug = filename_slug(primary_blogger_name(data), fallback="blogger", max_len=14)
        path = os.path.join(JSONS_DIR, f"result_{ts}_{keyword_slug}_{blogger_slug}_{identifier}.json")
        _display = os.path.basename(path)

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    html_path = os.path.splitext(path)[0] + ".html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(render_record_html(data, json_path=path))

    # 只在首次写入时追加 results.jsonl
    if not overwrite_json_path:
        lpath = os.path.join(JSONS_DIR, "results.jsonl")
        with open(lpath, "a", encoding="utf-8") as f:
            f.write(json.dumps(data, ensure_ascii=False) + "\n")

    print(f"[store] saved json: {path}")
    print(f"[store] saved html: {html_path}")
    return path


def build_video_identifier(data: dict) -> str:
    candidate = data.get("candidate", {}) or {}
    video = data.get("video_info", {}) or {}
    profile = data.get("profile_info", {}) or {}
    traffic = data.get("traffic_info", {}) or {}
    screenshots = data.get("screenshots", []) or []
    play_hash = first_play_screenshot_hash(screenshots)
    parts = [
        data.get("search_keyword", ""),
        candidate.get("title_text", ""),
        candidate.get("hit_text", ""),
        video.get("blogger_name", ""),
        profile.get("name", ""),
        video.get("video_channel_id", ""),
        profile.get("account", ""),
        video.get("publish_time", ""),
        traffic.get("marker_text", ""),
        play_hash,
        candidate.get("fingerprint", ""),
    ]
    raw = "|".join(str(part or "") for part in parts)
    return hashlib.sha1(raw.encode("utf-8")).hexdigest()[:16]


def first_play_screenshot_hash(paths: list) -> str:
    for path in paths or []:
        if not Path(path).name.lower().startswith("play_"):
            continue
        try:
            data = Path(path).read_bytes()
        except OSError:
            continue
        return hashlib.sha1(data).hexdigest()
    return ""


def primary_blogger_name(data: dict) -> str:
    video = data.get("video_info", {}) or {}
    profile = data.get("profile_info", {}) or {}
    traffic = data.get("traffic_info", {}) or {}
    return first_non_empty(
        video.get("blogger_name"),
        profile.get("name"),
        traffic.get("target_blogger_name"),
    )


def filename_slug(value: str, fallback: str, max_len: int = 14) -> str:
    value = re.sub(r'[\\/:*?"<>|\\s]+', "_", str(value or "").strip())
    value = value.strip("._")
    if not value:
        value = fallback
    return value[:max_len]


def load_seen(path=None):
    """Load collected fingerprints for duplicate detection."""
    if path is None:
        path = os.path.join(JSONS_DIR, "results.jsonl")
    seen = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    fp = d.get("candidate", {}).get("fingerprint", "")
                    if fp:
                        seen.add(fp)
                except json.JSONDecodeError:
                    continue
    print(f"[store] loaded seen fingerprints: {len(seen)}")
    return seen


def clear_seen(path=None):
    """清空历史指纹记录，每次新任务开始时调用。"""
    if path is None:
        path = os.path.join(JSONS_DIR, "results.jsonl")
    if os.path.exists(path):
        os.remove(path)
        # 创建空文件，确保后续追加写入正常
        with open(path, "w", encoding="utf-8") as f:
            f.write("")
        print(f"[store] cleared seen fingerprints")


def render_record_html(data: dict, json_path: str = "") -> str:
    title = first_non_empty(
        data.get("video_info", {}).get("title"),
        data.get("candidate", {}).get("title_text"),
        data.get("candidate", {}).get("hit_text"),
        "Weixin evidence record",
    )
    subtitle = first_non_empty(
        data.get("video_info", {}).get("blogger_name"),
        data.get("profile_info", {}).get("name"),
        data.get("traffic_info", {}).get("target_blogger_name"),
    )
    media = data.get("media_info", {}) or {}
    screenshots = data.get("screenshots", []) or []
    json_href = file_uri(json_path) if json_path else ""
    video_path = media.get("recording_video_path", "") or ""

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)}</title>
  <style>
    :root {{
      --bg: #f6f4ef;
      --paper: #fffdf8;
      --ink: #22211f;
      --muted: #6d675f;
      --line: #ddd5c8;
      --accent: #1f6f68;
      --accent-soft: #dfeeea;
      --warn: #9a5b13;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: radial-gradient(circle at top left, #ffffff 0, var(--bg) 38rem);
      color: var(--ink);
      font: 15px/1.6 "Microsoft YaHei", "PingFang SC", "Noto Sans CJK SC", sans-serif;
    }}
    main {{
      width: min(1180px, calc(100vw - 32px));
      margin: 28px auto 56px;
    }}
    header {{
      border-bottom: 2px solid var(--ink);
      padding-bottom: 18px;
      margin-bottom: 22px;
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: clamp(26px, 4vw, 42px);
      line-height: 1.12;
      letter-spacing: 0;
    }}
    h2 {{
      margin: 0 0 12px;
      font-size: 20px;
    }}
    h3 {{
      margin: 0 0 8px;
      font-size: 16px;
    }}
    a {{ color: var(--accent); }}
    .subtitle {{ color: var(--muted); font-size: 16px; }}
    .grid {{
      display: grid;
      grid-template-columns: minmax(0, 1.1fr) minmax(320px, 0.9fr);
      gap: 18px;
      align-items: start;
    }}
    section {{
      background: color-mix(in srgb, var(--paper) 92%, white);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 16px;
      margin-bottom: 18px;
      box-shadow: 0 12px 24px rgba(54, 45, 31, 0.05);
    }}
    .evidence-block {{
      display: grid;
      grid-template-columns: minmax(320px, 0.85fr) minmax(0, 1.15fr);
      gap: 16px;
    }}
    .evidence-text {{
      min-width: 0;
    }}
    .evidence-shots {{
      min-width: 0;
    }}
    dl {{
      display: grid;
      grid-template-columns: 118px minmax(0, 1fr);
      gap: 8px 12px;
      margin: 0;
    }}
    dt {{ color: var(--muted); }}
    dd {{ margin: 0; word-break: break-word; }}
    .pill {{
      display: inline-flex;
      align-items: center;
      min-height: 28px;
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 2px 10px;
      margin: 0 6px 6px 0;
      background: #fff;
      color: var(--muted);
      font-size: 13px;
    }}
    .video-box {{
      background: #111;
      border-radius: 8px;
      overflow: hidden;
      border: 1px solid #111;
    }}
    video {{
      display: block;
      width: 100%;
      max-height: 70vh;
      background: #111;
    }}
    .gallery {{
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
      gap: 12px;
    }}
    .shot-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 10px;
    }}
    figure {{
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 8px;
      overflow: hidden;
      background: #fff;
    }}
    figure img {{
      display: block;
      width: 100%;
      height: 260px;
      object-fit: contain;
      background: #171717;
    }}
    figcaption {{
      padding: 8px 10px;
      color: var(--muted);
      font-size: 12px;
      word-break: break-all;
    }}
    details {{
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fff;
      padding: 10px 12px;
    }}
    summary {{ cursor: pointer; color: var(--accent); font-weight: 700; }}
    pre {{
      margin: 12px 0 0;
      overflow: auto;
      white-space: pre-wrap;
      word-break: break-word;
      font-size: 12px;
      line-height: 1.5;
    }}
    .empty {{
      color: var(--warn);
      background: #fff8e8;
      border: 1px dashed #dfbd78;
      border-radius: 8px;
      padding: 12px;
    }}
    @media (max-width: 860px) {{
      main {{ width: min(100vw - 20px, 720px); margin-top: 18px; }}
      .grid {{ grid-template-columns: 1fr; }}
      .evidence-block {{ grid-template-columns: 1fr; }}
      dl {{ grid-template-columns: 112px minmax(0, 1fr); }}
      figure img {{ height: 220px; }}
    }}
  </style>
</head>
<body>
  <main>
    <header>
      <h1>{escape(title)}</h1>
      <div class="subtitle">{escape(subtitle)} {escape(data.get("capture_timestamp", ""))}</div>
    </header>
    {render_summary_section(data, json_href)}
    {render_video_section(video_path, media)}
    {render_evidence_sections(data, screenshots)}
    {render_raw_json_section(data)}
  </main>
</body>
</html>
"""


def render_summary_section(data: dict, json_href: str) -> str:
    candidate = data.get("candidate", {}) or {}
    video = data.get("video_info", {}) or {}
    media = data.get("media_info", {}) or {}
    rows = [
        ("搜索词", data.get("search_keyword", "")),
        ("视频标识符", candidate.get("video_identifier", "")),
        ("去重指纹", candidate.get("fingerprint", "")),
        ("视频链接", SafeHtml(link_or_text(video.get("video_link", "")))),
        ("录屏文件", SafeHtml(link_or_text(media.get("recording_video_path", "")))),
        ("JSON", SafeHtml(f'<a href="{json_href}">打开原始 JSON</a>') if json_href else ""),
    ]
    return render_dl_section("取证摘要", rows)


def render_video_section(video_path: str, media: dict) -> str:
    if not video_path:
        return '<section><h2>录屏</h2><div class="empty">未保存录屏文件路径。</div></section>'

    href = file_uri(video_path)
    meta = [
        ("开始时间", media.get("recording_started_at", "")),
        ("结束时间", media.get("recording_ended_at", "")),
        ("录制秒数", media.get("recording_duration_seconds", "")),
        ("是否有音频", media.get("has_audio", "")),
    ]
    return f"""
<section>
  <h2>录屏</h2>
  <div class="video-box">
    <video controls preload="metadata" src="{href}"></video>
  </div>
  <p><a href="{href}">{escape(video_path)}</a></p>
  {render_dl(meta)}
</section>
"""


def render_evidence_sections(data: dict, screenshots: list) -> str:
    groups = group_screenshots(screenshots)
    return "\n".join(
        [
            render_evidence_block("视频信息与互动数据", video_rows(data), groups["video"]),
            render_evidence_block("博主身份信息", author_rows(data), groups["author"]),
            render_evidence_block("引流账号与公司信息", traffic_rows(data), groups["traffic"]),
            render_asr_section(data),
            render_evidence_block("其他截图", [], groups["other"]) if groups["other"] else "",
        ]
    )


def render_asr_section(data: dict) -> str:
    """Render ASR transcript + script matching results."""
    media = data.get("media_info", {}) or {}
    asr_text = media.get("asr_text", "")
    script_match = media.get("script_match", {}) or {}
    if not asr_text and not script_match:
        return ""

    rows = [("ASR 转写文本", asr_text[:500] + ("…" if len(asr_text) > 500 else ""))]

    status = script_match.get("status", "")
    if status == "matched":
        best = script_match.get("best_match", {})
        rows.append(("剧本比对状态", "✅ 已匹配"))
        rows.append(("相似度", f"{best.get('similarity_score', 0):.1%}"))
        rows.append(("集号", best.get("episode", "")))
        rows.append(("场景", best.get("scene", "")))
        rows.append(("地点", best.get("location", "")))
        rows.append(("说话人", best.get("character", "")))
        rows.append(("出场人物", "、".join(best.get("characters", []) or [])))
        rows.append(("剧本原文", best.get("script_text", "")[:300] + ("…" if len(best.get("script_text", "")) > 300 else "")))

        candidates = script_match.get("top_candidates", []) or []
        if len(candidates) > 1:
            extra = []
            for i, c in enumerate(candidates[1:3], 2):
                extra.append(f"#{i} {c.get('similarity_score', 0):.1%} | {c.get('episode', '')} {c.get('scene', '')} | {c.get('script_text', '')[:80]}…")
            rows.append(("其他候选", "\n".join(extra)))
    elif status == "not_found":
        rows.append(("剧本比对状态", "⚠️ 未找到匹配"))
    elif status == "error":
        rows.append(("剧本比对状态", f"❌ 错误: {script_match.get('error', '')}"))
    elif status:
        rows.append(("剧本比对状态", status))

    return render_evidence_block("ASR 语音转写与剧本比对", rows, [])


def render_evidence_block(title: str, rows: list[tuple[str, object]], shots: list[str]) -> str:
    fields = render_dl(rows) if rows else '<div class="empty">暂无结构化文本字段。</div>'
    figures = render_figures(shots, compact=True) if shots else '<div class="empty">暂无对应截图。</div>'
    return f"""
<section>
  <h2>{escape(title)}</h2>
  <div class="evidence-block">
    <div class="evidence-text">{fields}</div>
    <div class="evidence-shots"><div class="shot-grid">{figures}</div></div>
  </div>
</section>
"""


def video_rows(data: dict) -> list[tuple[str, object]]:
    video = data.get("video_info", {}) or {}
    profile = data.get("profile_info", {}) or {}
    candidate = data.get("candidate", {}) or {}
    return [
        ("博主名称", first_non_empty(video.get("blogger_name"), profile.get("name"))),
        ("视频号ID", first_non_empty(video.get("video_channel_id"), profile.get("account"))),
        ("视频标题", first_non_empty(video.get("title"), candidate.get("title_text"), candidate.get("hit_text"))),
        ("发布时间", video.get("publish_time", "")),
        ("喜欢数", video.get("like_count", "")),
        ("收藏数", first_non_empty(video.get("favorite_count"), video.get("collect_count"), video.get("star_count"))),
        ("转发数", video.get("share_count", "")),
        ("评论数", video.get("comment_count", "")),
        ("视频链接", SafeHtml(link_or_text(video.get("video_link", "")))),
    ]


def author_rows(data: dict) -> list[tuple[str, object]]:
    video = data.get("video_info", {}) or {}
    profile = data.get("profile_info", {}) or {}
    return [
        ("博主名称", first_non_empty(profile.get("name"), video.get("blogger_name"))),
        ("视频号ID", first_non_empty(video.get("video_channel_id"), profile.get("account"))),
        ("主体类型", profile.get("subject_type", "")),
        ("企业全称", profile.get("company_full_name", "")),
        ("ID原文", video.get("video_channel_id_raw", "")),
        ("ID需复核", video.get("video_channel_id_needs_review", "")),
    ]


def traffic_rows(data: dict) -> list[tuple[str, object]]:
    traffic = data.get("traffic_info", {}) or {}
    return [
        ("存在引流", traffic.get("has_traffic_marker", "")),
        ("引流标记", traffic.get("marker_text", "")),
        ("目标博主", traffic.get("target_blogger_name", "")),
        ("目标视频号ID", traffic.get("target_video_channel_id", "")),
        ("ID原文", traffic.get("target_video_channel_id_raw", "")),
        ("ID需复核", traffic.get("target_video_channel_id_needs_review", "")),
        ("公司名", traffic.get("company_full_name", "")),
        ("认证时间", traffic.get("company_verified_at", "")),
    ]


def group_screenshots(paths: list) -> dict[str, list[str]]:
    groups = {"video": [], "author": [], "traffic": [], "other": []}
    for path in paths or []:
        name = Path(path).name.lower()
        if name.startswith(("play_", "share_", "share_copy_")):
            groups["video"].append(path)
        elif name.startswith(("profile_", "author_")):
            groups["author"].append(path)
        elif name.startswith("traffic_"):
            groups["traffic"].append(path)
        else:
            groups["other"].append(path)
    return groups


def render_screenshots_section(paths: list) -> str:
    if not paths:
        return '<section><h2>截图</h2><div class="empty">暂无截图。</div></section>'
    return f'<section><h2>截图</h2><div class="gallery">{render_figures(paths)}</div></section>'


def render_figures(paths: list, compact: bool = False) -> str:
    figures = []
    for path in paths:
        href = file_uri(path)
        caption = screenshot_label(path) if compact else Path(path).name
        figures.append(
            f'<figure><a href="{href}"><img src="{href}" loading="lazy" alt=""></a>'
            f'<figcaption>{escape(caption)}</figcaption></figure>'
        )
    return "".join(figures)


def screenshot_label(path: str) -> str:
    name = Path(path).name
    lower = name.lower()
    if lower.startswith("play_"):
        return "视频播放页截图"
    if lower.startswith("share_sheet_"):
        return "分享面板截图"
    if lower.startswith("share_copy_region_"):
        return "复制链接区域截图"
    if lower.startswith("profile_card_name_region_"):
        return "博主名称裁剪图"
    if lower.startswith("profile_card_"):
        return "博主资料卡截图"
    if lower.startswith("profile_info_"):
        return "博主更多信息页截图"
    if lower.startswith("traffic_marker_region_"):
        return "引流标记裁剪图"
    if lower.startswith("traffic_marker_full_"):
        return "引流标记整页截图"
    if lower.startswith("traffic_popup_"):
        return "traffic popup screenshot"
    if lower.startswith("traffic_landing_"):
        return "traffic landing screenshot"
    if lower.startswith("traffic_page_name_region_"):
        return "引流账号名称裁剪图"
    if lower.startswith("traffic_page_"):
        return "引流账号资料页截图"
    if lower.startswith("traffic_info_"):
        return "引流账号更多信息页截图"
    return name


def render_info_section(title: str, info: dict) -> str:
    rows = []
    for key, value in (info or {}).items():
        if key == "raw_ocr":
            continue
        rows.append((key, value))
    ocr_count = len((info or {}).get("raw_ocr") or [])
    if ocr_count:
        rows.append(("raw_ocr", f"{ocr_count} items"))
    return render_dl_section(title, rows)


def render_raw_json_section(data: dict) -> str:
    raw = escape(json.dumps(data, ensure_ascii=False, indent=2))
    return f"<section><h2>原始 JSON</h2><details><summary>展开完整记录</summary><pre>{raw}</pre></details></section>"


def render_dl_section(title: str, rows: list[tuple[str, object]]) -> str:
    return f"<section><h2>{escape(title)}</h2>{render_dl(rows)}</section>"


def render_dl(rows: list[tuple[str, object]]) -> str:
    body = []
    for key, value in rows:
        body.append(f"<dt>{escape(str(key))}</dt><dd>{format_value(value)}</dd>")
    return f"<dl>{''.join(body)}</dl>"


def format_value(value) -> str:
    if isinstance(value, SafeHtml):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return ""
    if isinstance(value, (int, float)):
        return escape(str(value))
    if isinstance(value, str):
        if not value:
            return ""
        return link_or_text(value)
    if isinstance(value, list):
        if not value:
            return ""
        if all(isinstance(item, dict) for item in value):
            return escape(json.dumps(value, ensure_ascii=False))
        return "".join(f'<span class="pill">{escape(str(item))}</span>' for item in value)
    if isinstance(value, dict):
        if not value:
            return ""
        return escape(json.dumps(value, ensure_ascii=False))
    return escape(str(value))


def link_or_text(value: str) -> str:
    value = value or ""
    if value.startswith(("http://", "https://")):
        return f'<a href="{escape(value)}">{escape(value)}</a>'
    if looks_like_path(value):
        href = file_uri(value)
        return f'<a href="{href}">{escape(value)}</a>'
    return escape(value)


def first_non_empty(*values: object) -> str:
    for value in values:
        text = str(value or "").strip()
        if text:
            return text
    return ""


def looks_like_path(value: str) -> bool:
    return bool(value) and (":\\" in value or value.startswith(("/", "./", "../")))


def file_uri(path: str) -> str:
    return Path(path).absolute().as_uri()


def escape(value: object) -> str:
    return html.escape(str(value or ""), quote=True)
